#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Reproduce Stage289 2026 live model artifacts from frozen historical feature matrices."""
from __future__ import annotations
import argparse,base64,gzip,json
from pathlib import Path
import numpy as np
import pandas as pd
from lightgbm import LGBMClassifier

def parse_args():
 p=argparse.ArgumentParser(); p.add_argument("--artifact-dir",required=True); p.add_argument("--output-dir",default=""); return p.parse_args()
def main():
 a=parse_args(); root=Path(a.artifact_dir).expanduser().resolve(); out=Path(a.output_dir).expanduser().resolve() if a.output_dir else Path(__file__).resolve().with_name("models")/"gold_v3_289"; out.mkdir(parents=True,exist_ok=True)
 src=pd.read_pickle(root/"gold_v3_stage280_oos_predictions.pkl"); features=pd.read_csv(root/"gold_v3_stage280_feature_importance.csv").feature.drop_duplicates().tolist(); z=src[(src.subtype=="REV")&(src.h4_align==-1)].copy(); test_start=pd.Timestamp("2026-01-01"); cal_start=test_start-pd.DateOffset(months=6); fit_start=max(z.time.min(),cal_start-pd.DateOffset(months=18)); fit=z[(z.time>=fit_start)&(z.time<cal_start)]; cal=z[(z.time>=cal_start)&(z.time<test_start)]; Xf=fit[features].replace([np.inf,-np.inf],np.nan).fillna(0).astype("float32"); yf=fit.target_rev.astype(int); Xc=cal[features].replace([np.inf,-np.inf],np.nan).fillna(0).astype("float32"); pos=max(int(yf.sum()),1); spw=min(max((len(yf)-pos)/pos,1),25)
 m280=LGBMClassifier(objective="binary",n_estimators=220,learning_rate=.03,num_leaves=15,max_depth=5,min_child_samples=60,subsample=.85,colsample_bytree=.8,reg_alpha=1,reg_lambda=6,random_state=281,n_jobs=1,verbosity=-1,scale_pos_weight=spw); m280.fit(Xf,yf); q95=float(np.quantile(m280.predict_proba(Xc)[:,1],.95)); (out/"stage280_rev_long_2026_model.txt.gz.b64").write_text(base64.b64encode(gzip.compress(m280.booster_.model_to_string().encode(),9)).decode(),encoding="ascii"); (out/"stage280_rev_long_2026_contract.json").write_text(json.dumps({"model":"STAGE280_REV_LONG_2026","features":features,"fit_start":str(fit_start),"fit_end_exclusive":str(cal_start),"cal_start":str(cal_start),"cal_end_exclusive":str(test_start),"score_quantile":"q95","score_threshold":q95,"params":m280.get_params()},ensure_ascii=False,indent=2,default=str),encoding="utf-8")
 ctx=pd.read_pickle(root/"gold_v3_stage281_m15_context.pkl"); wanted=Path(__file__).resolve().with_name("gold_v3_stage281_live_feature_list.txt").read_text().split(); base_features=[c for c in wanted if c in ctx.columns]; z=ctx[ctx.h4_trend==1].copy(); z["target"]=z.MED4H_long.astype("int8"); X=z[base_features].copy()
 for c in base_features:
  if any(k in c for k in ["ret","dist_ema","ema20_slope","ema50_slope","body_signed"]): X[c]=pd.to_numeric(X[c],errors="coerce")
  elif "_pos" in c: X[c]=2*pd.to_numeric(X[c],errors="coerce")-1
 X["countermove_30"]=-pd.to_numeric(X.get("m1_ret30",np.nan),errors="coerce"); X["countermove_60"]=-pd.to_numeric(X.get("m1_ret60",np.nan),errors="coerce"); X["countermove_120"]=-pd.to_numeric(X.get("m1_ret120",np.nan),errors="coerce"); X["turn_accel_m1"]=pd.to_numeric(X.get("m1_ret15",0),errors="coerce")-(pd.to_numeric(X.get("m1_ret60",0),errors="coerce")-pd.to_numeric(X.get("m1_ret15",0),errors="coerce"))/3; X["turn_accel_m5"]=pd.to_numeric(X.get("m5_ret3_atr",0),errors="coerce")-(pd.to_numeric(X.get("m5_ret12_atr",0),errors="coerce")-pd.to_numeric(X.get("m5_ret3_atr",0),errors="coerce"))/3; X["turn_accel_m15"]=pd.to_numeric(X.get("m15_ret1_atr",0),errors="coerce")-(pd.to_numeric(X.get("m15_ret4_atr",0),errors="coerce")-pd.to_numeric(X.get("m15_ret1_atr",0),errors="coerce"))/3; X["h4_align"]=z.h4_trend; X["d1_align"]=z.d1_trend; features281=list(X.columns); fm=(z.time>="2024-01-01")&(z.time<"2025-07-01"); cm=(z.time>="2025-07-01")&(z.time<"2026-01-01"); Xf=X.loc[fm].replace([np.inf,-np.inf],np.nan).fillna(0).astype("float32"); yf=z.loc[fm,"target"]; Xc=X.loc[cm].replace([np.inf,-np.inf],np.nan).fillna(0).astype("float32"); pos=max(int(yf.sum()),1); spw=min(max((len(yf)-pos)/pos,1),30); m281=LGBMClassifier(objective="binary",n_estimators=110,learning_rate=.045,num_leaves=15,max_depth=5,min_child_samples=120,subsample=.85,colsample_bytree=.75,reg_alpha=1.5,reg_lambda=8,random_state=281,n_jobs=1,verbosity=-1,scale_pos_weight=spw); m281.fit(Xf,yf); q85=float(np.quantile(m281.predict_proba(Xc)[:,1],.85)); (out/"stage281_med4h_cont_long_2026_model.txt.gz.b64").write_text(base64.b64encode(gzip.compress(m281.booster_.model_to_string().encode(),9)).decode(),encoding="ascii"); (out/"stage281_med4h_cont_long_2026_contract.json").write_text(json.dumps({"model":"STAGE281_MED4H_CONT_LONG_2026","features":features281,"fit_start":"2024-01-01","fit_end_exclusive":"2025-07-01","cal_start":"2025-07-01","cal_end_exclusive":"2026-01-01","score_quantile":"q85","score_threshold":q85,"params":m281.get_params()},ensure_ascii=False,indent=2,default=str),encoding="utf-8"); print(f"stage280_q95={q95:.12f}"); print(f"stage281_q85={q85:.12f}"); return 0
if __name__=="__main__": raise SystemExit(main())
