#!/usr/bin/env python3
# -*- coding: utf-8 -*-
r"""Build BTC strict-5 AI-tag numeric rules JSON for notification-time scoring.

Input is the deterministic numeric condition diagnostics CSV generated by:
  run_btc_strict_5_ai_tag_numeric_condition_diagnostics.py

Preferred input:
  btc_strict_5_ai_tag_numeric_condition_selected_candidates.csv
Fallback input:
  btc_strict_5_ai_tag_numeric_condition_summary.csv

Output is a compact JSON of rules that can be applied to a current preview row.
This does not call AI.
"""
from __future__ import annotations

import argparse
import json
import os
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import pandas as pd

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_CONDITION_CSV = Path("data/research_results/btc_strict_5_backtest_ai_review/ai_tag_numeric_condition_diagnostics/btc_strict_5_ai_tag_numeric_condition_selected_candidates.csv")
DEFAULT_OUTPUT_JSON = Path("data/runtime_state/btc/strict_5/ai_tag_numeric_rules.json")
DEFAULT_OUTPUT_CSV = Path("data/runtime_state/btc/strict_5/ai_tag_numeric_rules_summary.csv")
SCHEMA_VERSION = "btc_strict_5_ai_tag_numeric_rules_v2_fallback_summary"

FEATURE_ALIASES = {
    "h4_close_vs_ema20_atr": ["filter_feature_h4_close_vs_ema20_atr"],
    "h4_close_vs_ema50_atr": ["filter_feature_h4_close_vs_ema50_atr"],
    "m15_signal_candle_close_pos": ["trigger_close_pos"],
    "m15_signal_candle_range_atr_ratio": ["trigger_range_atr14", "range_atr14"],
    "m15_signal_candle_body_ratio": ["trigger_body_atr14", "body_atr14"],
    "m15_macd_hist_at_entry": ["trigger_macd_hist", "macd_hist"],
    "m15_macd_hist_delta_at_entry": ["trigger_macd_delta", "macd_hist_delta"],
}


def windows_long_path(path: str | Path) -> str:
    p = Path(path)
    if os.name != "nt":
        return str(p)
    text = str(p.resolve())
    if text.startswith("\\\\?\\"):
        return text
    if text.startswith("\\\\"):
        return "\\\\?\\UNC\\" + text.lstrip("\\")
    return "\\\\?\\" + text


def resolve(path: str | Path) -> Path:
    p = Path(path)
    return p if p.is_absolute() else REPO_ROOT / p


def mkdirp(path: str | Path) -> None:
    Path(windows_long_path(path)).mkdir(parents=True, exist_ok=True)


def write_json(path: str | Path, obj: dict[str, Any]) -> None:
    p = Path(path)
    mkdirp(p.parent)
    with open(windows_long_path(p), "w", encoding="utf-8", newline="") as f:
        json.dump(obj, f, ensure_ascii=False, indent=2, sort_keys=True, default=str)


def write_csv(df: pd.DataFrame, path: str | Path) -> None:
    p = Path(path)
    mkdirp(p.parent)
    df.to_csv(windows_long_path(p), index=False, encoding="utf-8-sig")


def utc_now_text() -> str:
    return datetime.now(UTC).strftime("%Y-%m-%d %H:%M:%S")


def read_csv_auto(path: str | Path) -> pd.DataFrame:
    return pd.read_csv(windows_long_path(path), encoding="utf-8-sig", sep=None, engine="python")


def clean_str(value: Any, default: str = "") -> str:
    if value is None:
        return default
    try:
        if pd.isna(value):
            return default
    except Exception:
        pass
    text = str(value).strip()
    return text if text else default


def safe_float(value: Any, default: float | None = None) -> float | None:
    try:
        if pd.isna(value):
            return default
    except Exception:
        pass
    try:
        return float(value)
    except Exception:
        return default


def selected_to_summary_path(path: Path) -> Path:
    name = path.name
    if name == "btc_strict_5_ai_tag_numeric_condition_selected_candidates.csv":
        return path.with_name("btc_strict_5_ai_tag_numeric_condition_summary.csv")
    return path


def resolve_existing_condition_csv(requested_path: Path) -> tuple[Path, str]:
    if requested_path.exists() and requested_path.is_file():
        return requested_path, "requested"
    summary_path = selected_to_summary_path(requested_path)
    if summary_path != requested_path and summary_path.exists() and summary_path.is_file():
        return summary_path, "fallback_condition_summary"
    # Also try the standard summary next to the requested directory.
    standard_summary = requested_path.parent / "btc_strict_5_ai_tag_numeric_condition_summary.csv"
    if standard_summary.exists() and standard_summary.is_file():
        return standard_summary, "fallback_standard_summary"
    raise FileNotFoundError(
        "condition CSV not found. requested="
        + str(requested_path)
        + " fallback_summary="
        + str(summary_path)
        + " standard_summary="
        + str(standard_summary)
    )


def parse_condition(row: pd.Series, suffix: str = "1") -> dict[str, Any] | None:
    feature = clean_str(row.get(f"feature_{suffix}"))
    op = clean_str(row.get(f"op_{suffix}"))
    threshold = safe_float(row.get(f"threshold_{suffix}"))
    if not feature or not op or threshold is None:
        return None
    return {"feature": feature, "op": op, "threshold": threshold, "aliases": FEATURE_ALIASES.get(feature, [])}


def candidate_sort_key(df: pd.DataFrame) -> pd.DataFrame:
    d = df.copy()
    for col in ["tag_precision", "tag_recall", "pf_delta", "kept_pf", "total_r_delta", "removed_trades"]:
        if col in d.columns:
            d[col] = pd.to_numeric(d[col], errors="coerce")
    grade_rank = {"A_NUMERIC_FILTER_CANDIDATE": 0, "B_WATCH_PF_DD_IMPROVES_TOTAL_R_DROPS": 1, "C_WATCH_DD_IMPROVES": 2}
    d["_grade_rank"] = d["diagnostic_grade"].map(grade_rank).fillna(9)
    d = d.sort_values(
        ["strategy_id", "tag_name", "tag_group", "_grade_rank", "tag_precision", "tag_recall", "pf_delta", "kept_pf"],
        ascending=[True, True, True, True, False, False, False, False],
    )
    return d


def build_rules(df: pd.DataFrame, args: argparse.Namespace) -> tuple[list[dict[str, Any]], pd.DataFrame]:
    work = df.copy()
    required = {"strategy_id", "tag_name", "tag_group", "diagnostic_grade", "feature_1", "op_1", "threshold_1"}
    missing = sorted(required - set(work.columns))
    if missing:
        raise ValueError(f"condition CSV missing required columns: {missing}")
    if args.allowed_grades:
        allowed = {x.strip() for x in args.allowed_grades.split(",") if x.strip()}
        work = work[work["diagnostic_grade"].astype(str).isin(allowed)].copy()
    for col in ["tag_precision", "tag_recall", "removed_trades", "kept_trades"]:
        if col in work.columns:
            work[col] = pd.to_numeric(work[col], errors="coerce")
    work = work[
        (work["tag_precision"].fillna(0) >= args.min_precision)
        & (work["tag_recall"].fillna(0) >= args.min_recall)
        & (work["removed_trades"].fillna(0) >= args.min_removed_trades)
    ].copy()
    work = candidate_sort_key(work)
    if args.max_rules_per_strategy_tag > 0:
        work = work.groupby(["strategy_id", "tag_name", "tag_group"], dropna=False).head(args.max_rules_per_strategy_tag).copy()
    rules: list[dict[str, Any]] = []
    summary_rows: list[dict[str, Any]] = []
    for i, (_, row) in enumerate(work.iterrows(), start=1):
        conditions = []
        c1 = parse_condition(row, "1")
        c2 = parse_condition(row, "2")
        if c1:
            conditions.append(c1)
        if c2:
            conditions.append(c2)
        if not conditions:
            continue
        grade = clean_str(row.get("diagnostic_grade"))
        severity = "FILTER" if grade.startswith("A_") else "WATCH"
        action = "BLOCKED_BY_OFFICIAL_FILTER" if severity == "FILTER" and clean_str(row.get("tag_name")) == "against_h4_context" else "WARN"
        rule = {
            "rule_id": f"BTC_STRICT5_TAG_RULE_{i:04d}",
            "symbol": "BTC",
            "strategy_id": clean_str(row.get("strategy_id")),
            "tag_name": clean_str(row.get("tag_name")),
            "tag_group": clean_str(row.get("tag_group")),
            "severity": severity,
            "action": action,
            "diagnostic_grade": grade,
            "condition_type": clean_str(row.get("condition_type")),
            "condition_text": clean_str(row.get("condition_text")),
            "conditions": conditions,
            "tag_precision": safe_float(row.get("tag_precision")),
            "tag_recall": safe_float(row.get("tag_recall")),
            "baseline_pf": safe_float(row.get("baseline_pf")),
            "kept_pf": safe_float(row.get("kept_pf")),
            "pf_delta": safe_float(row.get("pf_delta")),
            "baseline_total_r": safe_float(row.get("baseline_total_r")),
            "kept_total_r": safe_float(row.get("kept_total_r")),
            "total_r_delta": safe_float(row.get("total_r_delta")),
            "baseline_max_dd_r": safe_float(row.get("baseline_max_dd_r")),
            "kept_max_dd_r": safe_float(row.get("kept_max_dd_r")),
            "removed_trades": safe_float(row.get("removed_trades")),
            "kept_trades": safe_float(row.get("kept_trades")),
            "source": "btc_strict_5_ai_tag_numeric_condition_diagnostics",
            "note": "Deterministic numeric approximation of historical AI-review tag; no AI call at notification time.",
        }
        rules.append(rule)
        flat = {k: v for k, v in rule.items() if k != "conditions"}
        flat["conditions_json"] = json.dumps(conditions, ensure_ascii=False, default=str)
        summary_rows.append(flat)
    return rules, pd.DataFrame(summary_rows)


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Build BTC strict 5 AI-tag numeric rules JSON.")
    p.add_argument("--condition-csv", type=Path, default=DEFAULT_CONDITION_CSV)
    p.add_argument("--output-json", type=Path, default=DEFAULT_OUTPUT_JSON)
    p.add_argument("--output-csv", type=Path, default=DEFAULT_OUTPUT_CSV)
    p.add_argument("--allowed-grades", default="A_NUMERIC_FILTER_CANDIDATE,B_WATCH_PF_DD_IMPROVES_TOTAL_R_DROPS,C_WATCH_DD_IMPROVES")
    p.add_argument("--min-precision", type=float, default=0.60)
    p.add_argument("--min-recall", type=float, default=0.40)
    p.add_argument("--min-removed-trades", type=int, default=3)
    p.add_argument("--max-rules-per-strategy-tag", type=int, default=2)
    return p.parse_args()


def main() -> int:
    args = parse_args()
    requested_condition_csv = resolve(args.condition_csv)
    output_json = resolve(args.output_json)
    output_csv = resolve(args.output_csv)
    try:
        condition_csv, input_mode = resolve_existing_condition_csv(requested_condition_csv)
    except FileNotFoundError as exc:
        raise SystemExit(str(exc)) from exc
    df = read_csv_auto(condition_csv)
    rules, summary_df = build_rules(df, args)
    obj = {
        "schema_version": SCHEMA_VERSION,
        "created_at_utc": utc_now_text(),
        "cycle_ok": True,
        "symbol": "BTC",
        "requested_condition_csv": str(requested_condition_csv),
        "input_condition_csv": str(condition_csv),
        "input_mode": input_mode,
        "settings": {
            "allowed_grades": args.allowed_grades,
            "min_precision": float(args.min_precision),
            "min_recall": float(args.min_recall),
            "min_removed_trades": int(args.min_removed_trades),
            "max_rules_per_strategy_tag": int(args.max_rules_per_strategy_tag),
        },
        "rules_count": int(len(rules)),
        "rules": rules,
        "safety": {"ai_called": False, "mt5_calls": False, "order_send": False, "discord_send": False},
    }
    write_json(output_json, obj)
    write_csv(summary_df, output_csv)
    print(json.dumps({
        "cycle_ok": True,
        "schema_version": SCHEMA_VERSION,
        "rules_count": len(rules),
        "requested_condition_csv": str(requested_condition_csv),
        "input_condition_csv": str(condition_csv),
        "input_mode": input_mode,
        "output_json": str(output_json),
        "output_csv": str(output_csv),
    }, ensure_ascii=False, indent=2), flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
