#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
GOLD V2 Core/Tier2 audit-only evaluator.

This script does NOT call AI APIs, Discord, MT5 order APIs, or any live hooks.
It only reads prebuilt GOLD V2 cluster ledgers and re-scores the frozen policy:

    Core  = fold4_rules + ABC entry gate + CAP5 sizing
    Tier2 = Core REJECT rows where trend_eff96 <= 0.4 and ret96 <= -25, CAP3 sizing

Inputs expected by default:

    <input-dir>/abc_stack_cap_2025_fold4_cluster_ledger.csv
    <input-dir>/abc_stack_cap_2026_cluster_ledger.csv

These are generated by the prior stack-cap validation workflow.  The script is
kept intentionally separate from candle generation/re-exploration so it can be
rerun safely and deterministically on the same candidate universe.
"""

from __future__ import annotations

import argparse
import json
import math
import sys
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

import numpy as np
import pandas as pd


CORE_VIEW = "CORE_ABC_CAP5"
TIER2_VIEW = "TIER2_CAP3"
COMBINED_VIEW = "CORE_ABC_CAP5_PLUS_TIER2_CAP3"

REQUIRED_COLUMNS = [
    "entry_month",
    "signal_ABC",
    "trend_eff96",
    "ret96",
    "profit_cap3_from_members",
    "profit_cap5_from_members",
]

SORT_CANDIDATES = [
    "cluster_start",
    "top_entry_time",
    "close_time",
    "entry_time",
]


@dataclass
class InputAudit:
    dataset: str
    path: str
    rows: int
    missing_columns: List[str]
    duplicate_cluster_keys: Optional[int]
    first_month: Optional[str]
    last_month: Optional[str]
    status: str
    message: str


def parse_args(argv: Optional[Sequence[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Evaluate GOLD V2 Core+Tier2 audit-only policy")
    parser.add_argument(
        "--input-dir",
        default=None,
        help=(
            "Directory containing abc_stack_cap_2025_fold4_cluster_ledger.csv and "
            "abc_stack_cap_2026_cluster_ledger.csv. Default: <repo>/../../FX_OUTPUTS/"
            "gold_v2_ABC_stack_cap_2025_2026_validation_outputs"
        ),
    )
    parser.add_argument(
        "--output-dir",
        default=None,
        help="Output directory. Default: <repo>/../../FX_OUTPUTS/gold_v2_core_tier2_audit_only",
    )
    parser.add_argument("--tier2-trend-eff96-max", type=float, default=0.4)
    parser.add_argument("--tier2-ret96-max", type=float, default=-25.0)
    parser.add_argument("--strict", action="store_true", help="Fail if any required input is missing or has no rows")
    return parser.parse_args(argv)


def repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def files_dir_from_repo() -> Path:
    root = repo_root()
    # Typical layout: Files/xauusd-signal-lab-clean/xauusd-signal-lab
    # root.parents[1] => Files when clean clone is inside Files/xauusd-signal-lab-clean/xauusd-signal-lab
    if len(root.parents) >= 2:
        return root.parents[1]
    return root.parent


def default_input_dir() -> Path:
    return files_dir_from_repo() / "FX_OUTPUTS" / "gold_v2_ABC_stack_cap_2025_2026_validation_outputs"


def default_output_dir() -> Path:
    return files_dir_from_repo() / "FX_OUTPUTS" / "gold_v2_core_tier2_audit_only"


def to_number(series: pd.Series) -> pd.Series:
    return pd.to_numeric(series, errors="coerce")


def normalize_signal_column(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    if "signal_ABC" not in df.columns:
        if "signal_fixed_ABC" in df.columns:
            df["signal_ABC"] = df["signal_fixed_ABC"]
        elif "signal" in df.columns:
            df["signal_ABC"] = df["signal"]
        else:
            df["signal_ABC"] = "REJECT"
    df["signal_ABC"] = df["signal_ABC"].fillna("REJECT").astype(str)
    df.loc[df["signal_ABC"].isin(["", "nan", "None"]), "signal_ABC"] = "REJECT"
    return df


def sort_columns(df: pd.DataFrame) -> pd.DataFrame:
    for c in SORT_CANDIDATES:
        if c in df.columns:
            try:
                df[c] = pd.to_datetime(df[c], errors="coerce")
            except Exception:
                pass
            return df.sort_values(c).reset_index(drop=True)
    return df.reset_index(drop=True)


def metrics(values: Iterable[float]) -> Dict[str, float]:
    vals = pd.Series(list(values)).dropna().astype(float).to_numpy()
    n = int(len(vals))
    if n == 0:
        return {
            "count": 0,
            "win_rate": math.nan,
            "pf": math.nan,
            "total_r": 0.0,
            "avg_r": math.nan,
            "worst": math.nan,
            "best": math.nan,
            "maxdd": 0.0,
            "max_loss_streak": 0,
            "gross_win": 0.0,
            "gross_loss": 0.0,
        }
    gross_win = float(vals[vals > 0].sum())
    gross_loss = float(-vals[vals < 0].sum())
    if gross_loss == 0 and gross_win > 0:
        pf = math.inf
    elif gross_loss > 0:
        pf = gross_win / gross_loss
    else:
        pf = math.nan
    eq = np.cumsum(vals)
    previous_peak = np.maximum.accumulate(np.r_[0.0, eq[:-1]])
    dd = previous_peak - eq
    streak = 0
    max_streak = 0
    for v in vals:
        if v < 0:
            streak += 1
            max_streak = max(max_streak, streak)
        else:
            streak = 0
    return {
        "count": n,
        "win_rate": float((vals > 0).mean()),
        "pf": float(pf) if not math.isnan(pf) else math.nan,
        "total_r": float(vals.sum()),
        "avg_r": float(vals.mean()),
        "worst": float(vals.min()),
        "best": float(vals.max()),
        "maxdd": float(dd.max()) if len(dd) else 0.0,
        "max_loss_streak": int(max_streak),
        "gross_win": gross_win,
        "gross_loss": gross_loss,
    }


def audit_input(dataset: str, path: Path, df: Optional[pd.DataFrame]) -> InputAudit:
    if df is None:
        return InputAudit(dataset, str(path), 0, REQUIRED_COLUMNS, None, None, None, "ERROR", "file not loaded")
    missing = [c for c in REQUIRED_COLUMNS if c not in df.columns]
    duplicate_keys: Optional[int] = None
    key_cols = [c for c in ["dataset", "ruleset", "fold_id", "test_month", "cluster_id"] if c in df.columns]
    if "cluster_id" in df.columns:
        key_cols = [c for c in key_cols if c != "dataset"]
        if key_cols:
            duplicate_keys = int(df.duplicated(key_cols).sum())
    first_month = str(df["entry_month"].min()) if "entry_month" in df.columns and len(df) else None
    last_month = str(df["entry_month"].max()) if "entry_month" in df.columns and len(df) else None
    status = "OK" if not missing and len(df) > 0 else "ERROR"
    message = "" if status == "OK" else f"missing={missing} rows={len(df)}"
    return InputAudit(dataset, str(path), int(len(df)), missing, duplicate_keys, first_month, last_month, status, message)


def read_cluster_ledger(path: Path, dataset: str) -> Tuple[pd.DataFrame, InputAudit]:
    if not path.exists():
        return pd.DataFrame(), audit_input(dataset, path, None)
    df = pd.read_csv(path)
    df = normalize_signal_column(df)
    if "entry_month" not in df.columns:
        for c in SORT_CANDIDATES:
            if c in df.columns:
                dt = pd.to_datetime(df[c], errors="coerce")
                df["entry_month"] = dt.dt.to_period("M").astype(str)
                break
    for c in ["trend_eff96", "ret96", "profit_cap3_from_members", "profit_cap5_from_members"]:
        if c in df.columns:
            df[c] = to_number(df[c])
    df["dataset"] = dataset
    df = sort_columns(df)
    return df, audit_input(dataset, path, df)


def build_portfolio(df: pd.DataFrame, trend_max: float, ret_max: float) -> pd.DataFrame:
    d = df.copy()
    core_mask = d["signal_ABC"].fillna("REJECT").astype(str).ne("REJECT")
    tier2_mask = (
        (~core_mask)
        & d["trend_eff96"].le(trend_max)
        & d["ret96"].le(ret_max)
        & d["profit_cap3_from_members"].notna()
    )

    pieces: List[pd.DataFrame] = []

    core = d[core_mask].copy()
    if len(core):
        core["final_signal"] = "CORE_" + core["signal_ABC"].astype(str)
        core["priority"] = "HIGH"
        core["view"] = CORE_VIEW
        core["final_profit_r"] = np.where(
            core["signal_ABC"].astype(str).eq("A"),
            core["profit_cap5_from_members"],
            core["profit_cap3_from_members"],
        )
        pieces.append(core)

    tier2 = d[tier2_mask].copy()
    if len(tier2):
        tier2["final_signal"] = "TIER2_trend_eff96_le_0p4_ret96_le_m25"
        tier2["priority"] = "MEDIUM"
        tier2["view"] = TIER2_VIEW
        tier2["final_profit_r"] = tier2["profit_cap3_from_members"]
        pieces.append(tier2)

    if not pieces:
        return pd.DataFrame(columns=list(d.columns) + ["final_signal", "priority", "view", "final_profit_r"])

    portfolio = pd.concat(pieces, ignore_index=True)
    portfolio = sort_columns(portfolio)
    return portfolio


def summarize_aggregate(portfolio: pd.DataFrame) -> pd.DataFrame:
    rows: List[Dict[str, object]] = []
    for dataset, g in portfolio.groupby("dataset", dropna=False):
        for view_name, mask in [
            (CORE_VIEW, g["priority"].eq("HIGH")),
            (TIER2_VIEW, g["priority"].eq("MEDIUM")),
            (COMBINED_VIEW, pd.Series(True, index=g.index)),
        ]:
            gg = g[mask].copy()
            m = metrics(gg["final_profit_r"])
            m.update(
                {
                    "dataset": dataset,
                    "view": view_name,
                    "core_count": int(gg["priority"].eq("HIGH").sum()) if len(gg) else 0,
                    "tier2_count": int(gg["priority"].eq("MEDIUM").sum()) if len(gg) else 0,
                }
            )
            rows.append(m)
    out = pd.DataFrame(rows)
    return out.sort_values(["dataset", "view"]).reset_index(drop=True)


def summarize_monthly(portfolio: pd.DataFrame) -> pd.DataFrame:
    rows: List[Dict[str, object]] = []
    if portfolio.empty:
        return pd.DataFrame()
    for (dataset, month), g in portfolio.groupby(["dataset", "entry_month"], dropna=False):
        for view_name, mask in [
            (CORE_VIEW, g["priority"].eq("HIGH")),
            (TIER2_VIEW, g["priority"].eq("MEDIUM")),
            (COMBINED_VIEW, pd.Series(True, index=g.index)),
        ]:
            gg = g[mask].copy()
            m = metrics(gg["final_profit_r"])
            m.update(
                {
                    "dataset": dataset,
                    "month": month,
                    "view": view_name,
                    "core_count": int(gg["priority"].eq("HIGH").sum()) if len(gg) else 0,
                    "tier2_count": int(gg["priority"].eq("MEDIUM").sum()) if len(gg) else 0,
                }
            )
            rows.append(m)
    out = pd.DataFrame(rows)
    return out.sort_values(["dataset", "month", "view"]).reset_index(drop=True)


def summarize_signal(portfolio: pd.DataFrame) -> pd.DataFrame:
    rows: List[Dict[str, object]] = []
    if portfolio.empty:
        return pd.DataFrame()
    for (dataset, priority, signal), g in portfolio.groupby(["dataset", "priority", "final_signal"], dropna=False):
        m = metrics(g["final_profit_r"])
        m.update({"dataset": dataset, "priority": priority, "final_signal": signal})
        rows.append(m)
    return pd.DataFrame(rows).sort_values(["dataset", "priority", "final_signal"]).reset_index(drop=True)


def write_markdown_report(
    path: Path,
    aggregate: pd.DataFrame,
    monthly: pd.DataFrame,
    signal: pd.DataFrame,
    audits: List[InputAudit],
    trend_max: float,
    ret_max: float,
) -> None:
    def fmt_table(df: pd.DataFrame, cols: List[str]) -> str:
        if df.empty:
            return "_No rows._"
        view = df[cols].copy()
        if "win_rate" in view.columns:
            view["win_rate"] = (view["win_rate"] * 100).round(2)
        for c in ["pf", "total_r", "avg_r", "worst", "best", "maxdd", "gross_win", "gross_loss"]:
            if c in view.columns:
                view[c] = view[c].astype(float).round(2)
        return view.to_markdown(index=False)

    lines: List[str] = []
    lines.append("# GOLD V2 Core/Tier2 audit-only evaluator report")
    lines.append("")
    lines.append(f"Created UTC: {datetime.now(timezone.utc).isoformat()}")
    lines.append("")
    lines.append("## Frozen policy")
    lines.append("")
    lines.append("```text")
    lines.append("Core / HIGH:")
    lines.append("  signal_ABC != REJECT")
    lines.append("  A uses profit_cap5_from_members")
    lines.append("  B/C use profit_cap3_from_members")
    lines.append("")
    lines.append("Tier2 / MEDIUM:")
    lines.append(f"  signal_ABC == REJECT")
    lines.append(f"  trend_eff96 <= {trend_max}")
    lines.append(f"  ret96 <= {ret_max}")
    lines.append("  uses profit_cap3_from_members")
    lines.append("```")
    lines.append("")
    lines.append("## Input audit")
    lines.append("")
    lines.append(pd.DataFrame([asdict(a) for a in audits]).to_markdown(index=False))
    lines.append("")
    lines.append("## Aggregate")
    lines.append("")
    lines.append(
        fmt_table(
            aggregate,
            ["dataset", "view", "count", "win_rate", "pf", "total_r", "avg_r", "worst", "maxdd", "max_loss_streak", "core_count", "tier2_count"],
        )
    )
    lines.append("")
    lines.append("## Monthly")
    lines.append("")
    lines.append(
        fmt_table(
            monthly,
            ["dataset", "month", "view", "count", "win_rate", "pf", "total_r", "worst", "maxdd", "core_count", "tier2_count"],
        )
    )
    lines.append("")
    lines.append("## Signal breakdown")
    lines.append("")
    lines.append(
        fmt_table(
            signal,
            ["dataset", "priority", "final_signal", "count", "win_rate", "pf", "total_r", "worst", "maxdd"],
        )
    )
    lines.append("")
    lines.append("## Safety note")
    lines.append("")
    lines.append("This is audit-only. It does not approve runtime, Discord, or MT5 order integration.")
    path.write_text("\n".join(lines), encoding="utf-8")


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = parse_args(argv)
    input_dir = Path(args.input_dir).expanduser().resolve() if args.input_dir else default_input_dir()
    output_dir = Path(args.output_dir).expanduser().resolve() if args.output_dir else default_output_dir()
    output_dir.mkdir(parents=True, exist_ok=True)

    inputs = [
        ("2025_fold4", input_dir / "abc_stack_cap_2025_fold4_cluster_ledger.csv"),
        ("2026_WF", input_dir / "abc_stack_cap_2026_cluster_ledger.csv"),
    ]

    dataframes: List[pd.DataFrame] = []
    audits: List[InputAudit] = []
    for dataset, path in inputs:
        df, audit = read_cluster_ledger(path, dataset)
        audits.append(audit)
        if audit.status == "OK":
            dataframes.append(df)
        print(f"[INPUT] {dataset}: status={audit.status} rows={audit.rows} path={path}")
        if audit.message:
            print(f"        {audit.message}")

    if args.strict and any(a.status != "OK" for a in audits):
        print("[ERROR] Strict mode: input audit failed", file=sys.stderr)
        return 2
    if not dataframes:
        print("[ERROR] No valid input ledgers loaded", file=sys.stderr)
        return 2

    portfolio_parts = [build_portfolio(df, args.tier2_trend_eff96_max, args.tier2_ret96_max) for df in dataframes]
    portfolio = pd.concat(portfolio_parts, ignore_index=True) if portfolio_parts else pd.DataFrame()
    portfolio = sort_columns(portfolio)

    aggregate = summarize_aggregate(portfolio)
    monthly = summarize_monthly(portfolio)
    signal = summarize_signal(portfolio)

    portfolio.to_csv(output_dir / "core_tier2_portfolio_ledger.csv", index=False, encoding="utf-8-sig")
    aggregate.to_csv(output_dir / "core_tier2_aggregate_summary.csv", index=False, encoding="utf-8-sig")
    monthly.to_csv(output_dir / "core_tier2_monthly_summary.csv", index=False, encoding="utf-8-sig")
    signal.to_csv(output_dir / "core_tier2_signal_breakdown.csv", index=False, encoding="utf-8-sig")
    pd.DataFrame([asdict(a) for a in audits]).to_csv(output_dir / "core_tier2_input_audit.csv", index=False, encoding="utf-8-sig")

    summary = {
        "created_utc": datetime.now(timezone.utc).isoformat(),
        "status": "AUDIT_ONLY",
        "input_dir": str(input_dir),
        "output_dir": str(output_dir),
        "policy": {
            "core": "signal_ABC != REJECT; A uses CAP5; B/C use CAP3",
            "tier2": f"signal_ABC == REJECT AND trend_eff96 <= {args.tier2_trend_eff96_max} AND ret96 <= {args.tier2_ret96_max}; uses CAP3",
        },
        "input_audit": [asdict(a) for a in audits],
        "aggregate": aggregate.replace({np.nan: None, np.inf: "inf", -np.inf: "-inf"}).to_dict(orient="records"),
    }
    (output_dir / "core_tier2_summary.json").write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")
    write_markdown_report(
        output_dir / "GOLD_V2_CORE_TIER2_AUDIT_ONLY_REPORT.md",
        aggregate,
        monthly,
        signal,
        audits,
        args.tier2_trend_eff96_max,
        args.tier2_ret96_max,
    )

    print(f"[DONE] output_dir={output_dir}")
    print(aggregate[["dataset", "view", "count", "win_rate", "pf", "total_r", "worst", "maxdd", "core_count", "tier2_count"]].to_string(index=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
