#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Candidate normalizer for Mochipoyo full/minimal scanner comparison.

This module does not generate trade signals.  Its job is to normalize candidate
rows produced by different scanner paths into one stable schema so the upcoming
full strict scan vs minimal scan comparison can compare like-for-like rows.

Design rules:
- Do not change signal logic here.
- Do not filter by source_filter_name here.
- Do not send Discord messages here.
- payload_key is generated by mochipoyo_payload_key.py only.
- risk OK/NG split is a mechanical split on normalized risk_status.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Iterable, Mapping, Sequence

import pandas as pd

try:  # Package import when called from repository root.
    from scripts.mochipoyo_minimal_config import get_pair_config
    from scripts.mochipoyo_payload_key import apply_payload_key_to_dataframe
except ModuleNotFoundError:  # Direct script import/execution from inside scripts/.
    from mochipoyo_minimal_config import get_pair_config  # type: ignore
    from mochipoyo_payload_key import apply_payload_key_to_dataframe  # type: ignore

NORMALIZED_BASE_COLUMNS: list[str] = [
    "symbol",
    "mt5_symbol",
    "pair_name",
    "candidate_rank",
    "direction",
    "signal_close_time",
    "entry_time",
    "entry_price",
    "entry_price_normalized",
    "sl_price",
    "tp_price",
    "risk_status",
    "payload_key",
    "payload_key_status",
    "payload_key_error_reason",
    "reason_text",
    "auto_trade_enabled",
    "auto_trade_eligible",
    "auto_trade_reject_reason",
]

NORMALIZED_CONFIRMED_TIME_COLUMNS: list[str] = [
    "base_time",
    "base_close_time",
    "context_time",
    "context_close_time",
    "signal_time",
    "pivot_time",
    "pivot_confirmed_time",
]

NORMALIZED_RISK_COLUMNS: list[str] = [
    "risk_reject_reason",
    "risk_distance",
    "reward_distance",
    "rr",
]

NORMALIZED_BTC_SPREAD_COLUMNS: list[str] = [
    "current_spread_points",
    "current_spread_price",
    "mode_spread_points",
    "mode_spread_price",
    "effective_spread_price",
    "spread_to_sl_ratio",
    "spread_to_tp_ratio",
    "effective_rr_after_spread",
    "net_sl_after_spread_price",
    "net_tp_after_spread_price",
]

NORMALIZED_EXTRA_COLUMNS: list[str] = [
    "selected_slice",
    "source_filter_name",
    "normalizer_source",
    "normalizer_status",
    "normalizer_error_reason",
]

NORMALIZED_COLUMNS: list[str] = (
    NORMALIZED_BASE_COLUMNS
    + NORMALIZED_CONFIRMED_TIME_COLUMNS
    + NORMALIZED_RISK_COLUMNS
    + NORMALIZED_BTC_SPREAD_COLUMNS
    + NORMALIZED_EXTRA_COLUMNS
)

TIME_COLUMNS: set[str] = {
    "signal_close_time",
    "entry_time",
    "base_time",
    "base_close_time",
    "context_time",
    "context_close_time",
    "signal_time",
    "pivot_time",
    "pivot_confirmed_time",
}

NUMERIC_COLUMNS: set[str] = {
    "entry_price",
    "sl_price",
    "tp_price",
    "risk_distance",
    "reward_distance",
    "rr",
    "current_spread_points",
    "current_spread_price",
    "mode_spread_points",
    "mode_spread_price",
    "effective_spread_price",
    "spread_to_sl_ratio",
    "spread_to_tp_ratio",
    "effective_rr_after_spread",
    "net_sl_after_spread_price",
    "net_tp_after_spread_price",
}

STRING_COLUMNS: set[str] = {
    "symbol",
    "mt5_symbol",
    "pair_name",
    "candidate_rank",
    "direction",
    "entry_price_normalized",
    "risk_status",
    "payload_key",
    "payload_key_status",
    "payload_key_error_reason",
    "reason_text",
    "auto_trade_reject_reason",
    "risk_reject_reason",
    "selected_slice",
    "source_filter_name",
    "normalizer_source",
    "normalizer_status",
    "normalizer_error_reason",
}

BOOL_COLUMNS: set[str] = {
    "auto_trade_enabled",
    "auto_trade_eligible",
}

# Common aliases seen in existing scripts and expected minimal scanner rows.
COLUMN_ALIASES: dict[str, str] = {
    "rank": "candidate_rank",
    "candidate": "candidate_rank",
    "side": "direction",
    "order_side": "direction",
    "signal_direction": "direction",
    "time": "entry_time",
    "timestamp": "entry_time",
    "datetime": "entry_time",
    "price": "entry_price",
    "entry": "entry_price",
    "sl": "sl_price",
    "stop_loss": "sl_price",
    "stop_loss_price": "sl_price",
    "tp": "tp_price",
    "take_profit": "tp_price",
    "take_profit_price": "tp_price",
    "live_risk_status": "risk_status",
    "btc_live_risk_status": "risk_status",
    "status": "risk_status",
    "reason": "reason_text",
    "message": "reason_text",
    "filter_name": "source_filter_name",
    "gross_sl_distance_price": "risk_distance",
    "gross_tp_distance_price": "reward_distance",
    "mode_spread": "mode_spread_points",
    "mode_spread_point": "mode_spread_points",
    "mode_spread_price_value": "mode_spread_price",
}


@dataclass(frozen=True)
class NormalizeResult:
    df: pd.DataFrame
    source: str
    rows_in: int
    rows_out: int
    ok_rows: int
    invalid_payload_rows: int


def _lower_strip_columns(columns: Iterable[object]) -> list[str]:
    out: list[str] = []
    for col in columns:
        name = str(col).strip()
        low = name.lower()
        out.append(COLUMN_ALIASES.get(low, low))
    return out


def _first_existing(df: pd.DataFrame, names: Sequence[str]) -> str | None:
    for name in names:
        if name in df.columns:
            return name
    return None


def _series_from_existing_or_na(df: pd.DataFrame, names: Sequence[str]) -> pd.Series:
    col = _first_existing(df, names)
    if col is None:
        return pd.Series([pd.NA] * len(df), index=df.index)
    return df[col]


def _coerce_datetime_series(values: pd.Series) -> pd.Series:
    return pd.to_datetime(values, errors="coerce")


def _coerce_numeric_series(values: pd.Series) -> pd.Series:
    return pd.to_numeric(values, errors="coerce")


def _coerce_string_series(values: pd.Series) -> pd.Series:
    # Keep missing values as <NA> rather than string "nan".
    out = values.copy()
    mask = out.isna()
    out = out.astype("string").str.strip()
    out[mask] = pd.NA
    out = out.mask(out == "", pd.NA)
    return out


def _coerce_bool_series(values: pd.Series, default: bool | None = None) -> pd.Series:
    if values.isna().all():
        fill_value = pd.NA if default is None else bool(default)
        return pd.Series([fill_value] * len(values), index=values.index)
    def parse_one(value: Any) -> bool | pd.NA:
        if pd.isna(value):
            return pd.NA if default is None else bool(default)
        text = str(value).strip().lower()
        if text in {"1", "true", "yes", "y", "on"}:
            return True
        if text in {"0", "false", "no", "n", "off"}:
            return False
        return pd.NA if default is None else bool(default)
    return values.map(parse_one)


def _normalize_basic_columns(df: pd.DataFrame) -> pd.DataFrame:
    work = df.copy()
    work.columns = _lower_strip_columns(work.columns)
    return work


def _derive_selected_slice(df: pd.DataFrame) -> pd.Series:
    if "selected_slice" in df.columns:
        return _coerce_string_series(df["selected_slice"])
    if {"pair_name", "candidate_rank", "direction"}.issubset(df.columns):
        parts = []
        for col in ("pair_name", "candidate_rank", "direction"):
            parts.append(_coerce_string_series(df[col]).str.upper())
        return parts[0] + "|" + parts[1] + "|" + parts[2]
    return pd.Series([pd.NA] * len(df), index=df.index)


def _derive_signal_close_time(df: pd.DataFrame) -> pd.Series:
    # Prefer explicit signal_close_time.  Fall back to close/base/entry time for
    # legacy payloads that only had entry_time.
    return _series_from_existing_or_na(
        df,
        ["signal_close_time", "signal_close", "base_close_time", "entry_time"],
    )


def _derive_pair_defaults(df: pd.DataFrame) -> tuple[pd.Series, pd.Series, pd.Series]:
    """Derive mt5_symbol, auto_trade_enabled, auto_trade_eligible from pair config.

    auto_trade_eligible defaults to False unless the row explicitly provides it.
    This keeps auto-trade safely disabled in all current normalizer output.
    """
    mt5_symbols: list[Any] = []
    auto_enabled: list[bool] = []
    for _, row in df.iterrows():
        pair_name = row.get("pair_name")
        try:
            cfg = get_pair_config(str(pair_name))
            mt5_symbols.append(cfg.get("mt5_symbol"))
            auto_enabled.append(bool(cfg.get("auto_trade_enabled", False)))
        except Exception:
            mt5_symbols.append(pd.NA)
            auto_enabled.append(False)

    if "mt5_symbol" in df.columns:
        mt5 = _coerce_string_series(df["mt5_symbol"]).fillna(pd.Series(mt5_symbols, index=df.index, dtype="string"))
    else:
        mt5 = pd.Series(mt5_symbols, index=df.index, dtype="string")

    if "auto_trade_enabled" in df.columns:
        enabled = _coerce_bool_series(df["auto_trade_enabled"], default=False)
    else:
        enabled = pd.Series(auto_enabled, index=df.index)

    if "auto_trade_eligible" in df.columns:
        eligible = _coerce_bool_series(df["auto_trade_eligible"], default=False)
    else:
        eligible = pd.Series([False] * len(df), index=df.index)
    return mt5, enabled, eligible


def _apply_schema(df: pd.DataFrame, source: str) -> pd.DataFrame:
    work = _normalize_basic_columns(df)
    out = pd.DataFrame(index=work.index)

    # Core identity fields.
    out["symbol"] = _coerce_string_series(_series_from_existing_or_na(work, ["symbol"])).str.upper()
    out["pair_name"] = _coerce_string_series(_series_from_existing_or_na(work, ["pair_name"])).str.upper()
    out["candidate_rank"] = _coerce_string_series(_series_from_existing_or_na(work, ["candidate_rank"])).str.upper()
    out["direction"] = _coerce_string_series(_series_from_existing_or_na(work, ["direction"])).str.upper()

    # Times.
    out["signal_close_time"] = _coerce_datetime_series(_derive_signal_close_time(work))
    out["entry_time"] = _coerce_datetime_series(_series_from_existing_or_na(work, ["entry_time"]))
    for col in NORMALIZED_CONFIRMED_TIME_COLUMNS:
        if col in {"signal_time"}:
            out[col] = _coerce_datetime_series(_series_from_existing_or_na(work, [col, "signal_close_time", "entry_time"]))
        else:
            out[col] = _coerce_datetime_series(_series_from_existing_or_na(work, [col]))

    # Prices / risk / spread numbers.
    numeric_source_map: dict[str, list[str]] = {
        "entry_price": ["entry_price"],
        "sl_price": ["sl_price"],
        "tp_price": ["tp_price"],
        "risk_distance": ["risk_distance", "gross_sl_distance_price"],
        "reward_distance": ["reward_distance", "gross_tp_distance_price"],
        "rr": ["rr"],
        "current_spread_points": ["current_spread_points"],
        "current_spread_price": ["current_spread_price"],
        "mode_spread_points": ["mode_spread_points"],
        "mode_spread_price": ["mode_spread_price"],
        "effective_spread_price": ["effective_spread_price"],
        "spread_to_sl_ratio": ["spread_to_sl_ratio"],
        "spread_to_tp_ratio": ["spread_to_tp_ratio"],
        "effective_rr_after_spread": ["effective_rr_after_spread"],
        "net_sl_after_spread_price": ["net_sl_after_spread_price"],
        "net_tp_after_spread_price": ["net_tp_after_spread_price"],
    }
    for col, names in numeric_source_map.items():
        out[col] = _coerce_numeric_series(_series_from_existing_or_na(work, names))

    # Status/text fields.
    risk_status_source = _series_from_existing_or_na(work, ["risk_status", "live_risk_status", "btc_live_risk_status"])
    out["risk_status"] = _coerce_string_series(risk_status_source).str.upper()
    out["risk_reject_reason"] = _coerce_string_series(_series_from_existing_or_na(work, ["risk_reject_reason", "reject_reason"]))
    out["reason_text"] = _coerce_string_series(_series_from_existing_or_na(work, ["reason_text"])).fillna("")
    out["source_filter_name"] = _coerce_string_series(_series_from_existing_or_na(work, ["source_filter_name"]))
    out["selected_slice"] = _derive_selected_slice(work)

    mt5_symbol, auto_enabled, auto_eligible = _derive_pair_defaults(out.join(work, rsuffix="_src"))
    out["mt5_symbol"] = mt5_symbol
    out["auto_trade_enabled"] = auto_enabled
    out["auto_trade_eligible"] = auto_eligible
    out["auto_trade_reject_reason"] = _coerce_string_series(_series_from_existing_or_na(work, ["auto_trade_reject_reason"]))

    out["normalizer_source"] = source
    out["normalizer_status"] = "OK"
    out["normalizer_error_reason"] = pd.NA

    # Preserve existing payload fields only until rebuilt below.
    if "payload_key" in work.columns:
        out["payload_key_original"] = work["payload_key"]

    # Apply stable payload_key using pair-specific price_digits when possible.
    out = apply_payload_keys_by_pair(out)

    # Mark rows with invalid payload_key as invalid normalizer rows, but keep them
    # in the output for audit/debugging.
    invalid_payload = out["payload_key_status"].astype(str) != "OK"
    out.loc[invalid_payload, "normalizer_status"] = "INVALID_PAYLOAD_KEY"
    out.loc[invalid_payload, "normalizer_error_reason"] = out.loc[invalid_payload, "payload_key_error_reason"]

    return ensure_normalized_columns(out)


def apply_payload_keys_by_pair(df: pd.DataFrame, default_price_digits: int = 2) -> pd.DataFrame:
    """Apply payload keys, using pair config price_digits per row when available."""
    frames: list[pd.DataFrame] = []
    if df.empty:
        return apply_payload_key_to_dataframe(df, price_digits=default_price_digits)
    work = df.copy()
    pair_series = work.get("pair_name", pd.Series([pd.NA] * len(work), index=work.index))
    for pair_name, part in work.groupby(pair_series.fillna("__MISSING_PAIR__"), dropna=False, sort=False):
        price_digits = default_price_digits
        try:
            if str(pair_name) != "__MISSING_PAIR__":
                price_digits = int(get_pair_config(str(pair_name)).get("price_digits", default_price_digits))
        except Exception:
            price_digits = default_price_digits
        frames.append(apply_payload_key_to_dataframe(part, price_digits=price_digits))
    if not frames:
        return apply_payload_key_to_dataframe(work, price_digits=default_price_digits)
    return pd.concat(frames, axis=0).sort_index()


def ensure_normalized_columns(df: pd.DataFrame) -> pd.DataFrame:
    out = df.copy()
    for col in NORMALIZED_COLUMNS:
        if col not in out.columns:
            out[col] = pd.NA

    # Coerce canonical columns one last time.
    for col in TIME_COLUMNS:
        if col in out.columns:
            out[col] = pd.to_datetime(out[col], errors="coerce")
    for col in NUMERIC_COLUMNS:
        if col in out.columns:
            out[col] = pd.to_numeric(out[col], errors="coerce")
    for col in STRING_COLUMNS:
        if col in out.columns:
            out[col] = _coerce_string_series(out[col])
    for col in BOOL_COLUMNS:
        if col in out.columns:
            out[col] = _coerce_bool_series(out[col], default=False)

    # Keep canonical columns first, but do not discard diagnostic extras like
    # payload_key_original if present.
    extras = [c for c in out.columns if c not in NORMALIZED_COLUMNS]
    return out[NORMALIZED_COLUMNS + extras]


def normalize_full_strict_candidates(df: pd.DataFrame) -> pd.DataFrame:
    """Normalize rows produced by the existing full strict dry-run path."""
    return _apply_schema(df, source="full_strict")


def normalize_minimal_candidates(df: pd.DataFrame) -> pd.DataFrame:
    """Normalize rows produced by the future minimal scanner path."""
    return _apply_schema(df, source="minimal")


def normalize_candidates(df: pd.DataFrame, source: str) -> NormalizeResult:
    """Normalize arbitrary candidate rows and return summary metadata."""
    rows_in = int(len(df))
    normalized = _apply_schema(df, source=source)
    rows_out = int(len(normalized))
    ok_rows = int((normalized["normalizer_status"].astype(str) == "OK").sum()) if rows_out else 0
    invalid_payload_rows = int((normalized["payload_key_status"].astype(str) != "OK").sum()) if rows_out else 0
    return NormalizeResult(
        df=normalized,
        source=source,
        rows_in=rows_in,
        rows_out=rows_out,
        ok_rows=ok_rows,
        invalid_payload_rows=invalid_payload_rows,
    )


def split_risk_ok_ng(df: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Split normalized candidates into risk OK and risk NG DataFrames."""
    if df.empty:
        return df.copy(), df.copy()
    status = df.get("risk_status", pd.Series([pd.NA] * len(df), index=df.index)).astype("string").str.upper()
    ok_mask = status == "OK"
    return df.loc[ok_mask].copy(), df.loc[~ok_mask].copy()


def filter_allowed_slices(df: pd.DataFrame, allowed_slices: Iterable[str | Mapping[str, Any]]) -> pd.DataFrame:
    """Filter already-normalized rows by allowed slice strings or mappings."""
    if df.empty:
        return df.copy()
    allowed_set: set[str] = set()
    for row in allowed_slices:
        if isinstance(row, str):
            allowed_set.add(row.strip().upper())
        else:
            pair = str(row.get("pair_name", "")).strip().upper()
            rank = str(row.get("candidate_rank", "")).strip().upper()
            direction = str(row.get("direction", "")).strip().upper()
            allowed_set.add(f"{pair}|{rank}|{direction}")
    selected = df.get("selected_slice")
    if selected is None:
        return df.iloc[0:0].copy()
    return df[selected.astype("string").str.upper().isin(allowed_set)].copy()


__all__ = [
    "NORMALIZED_BASE_COLUMNS",
    "NORMALIZED_BTC_SPREAD_COLUMNS",
    "NORMALIZED_COLUMNS",
    "NORMALIZED_CONFIRMED_TIME_COLUMNS",
    "NORMALIZED_RISK_COLUMNS",
    "NormalizeResult",
    "apply_payload_keys_by_pair",
    "ensure_normalized_columns",
    "filter_allowed_slices",
    "normalize_candidates",
    "normalize_full_strict_candidates",
    "normalize_minimal_candidates",
    "split_risk_ok_ng",
]
