#!/usr/bin/env python3
# -*- coding: utf-8 -*-
r"""Add GOLD strict-7 AI tag-combination rules to ai_tag_numeric_rules.json.

This script is intentionally post-processing only:
- input: completed GOLD strict-7 AI review feature snapshot + review ledger
- input/output: existing ai_tag_numeric_rules.json generated by build_gold_strict_7_ai_tag_numeric_rules.py
- output: same JSON with combo_rules appended/replaced
- output: combo summary CSV for audit

No AI call. No MT5 call. No Discord. No order_send.

Why separate from the single-tag builder?
- Keeps the current single-tag rule builder stable.
- Makes combo logic easy to audit and disable.
- Lets notification-time scoring remain deterministic.
"""
from __future__ import annotations

import argparse
import itertools
import json
import os
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import pandas as pd

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_AI_REVIEW_DIR = Path("data/runtime_logs/trade_ai_review_backtest_gold_strict_7")
DEFAULT_RULE_JSON = Path("data/runtime_state/gold/strict_7/ai_tag_numeric_rules.json")
DEFAULT_OUTPUT_CSV = Path("data/runtime_state/gold/strict_7/ai_tag_combo_rules_summary.csv")
SCHEMA_VERSION = "gold_strict_7_ai_tag_combo_rules_v1_strategy_relative_pairs_triples"

NON_INFORMATIVE_TAGS = {
    "", "-", "none", "null", "n/a", "na", "unknown", "unclear",
    "no_clear_positive_tag", "no_positive_tag", "no_risk_tag", "no_clear_risk_tag",
}

POSITIVE_TAG_GROUPS = {"positive", "good", "support"}
TAG_GROUPS_TO_USE = {"risk", "execution", "system", "positive"}


def windows_long_path(path: str | Path) -> str:
    p = Path(path)
    if os.name != "nt":
        return str(p)
    text = str(p.resolve())
    if text.startswith("\\\\?\\"):
        return text
    if text.startswith("\\\\"):
        return "\\\\?\\UNC\\" + text.lstrip("\\")
    return "\\\\?\\" + text


def resolve(path: str | Path) -> Path:
    p = Path(path)
    return p if p.is_absolute() else REPO_ROOT / p


def mkdirp(path: str | Path) -> None:
    Path(windows_long_path(path)).mkdir(parents=True, exist_ok=True)


def utc_now_text() -> str:
    return datetime.now(UTC).strftime("%Y-%m-%d %H:%M:%S")


def clean_str(value: Any, default: str = "") -> str:
    if value is None:
        return default
    try:
        if pd.isna(value):
            return default
    except Exception:
        pass
    text = str(value).strip()
    return text if text else default


def canonical_tag(tag: Any) -> str:
    return clean_str(tag).lower().replace(" ", "_").replace("-", "_")


def is_informative_tag(tag: Any) -> bool:
    return canonical_tag(tag) not in NON_INFORMATIVE_TAGS


def safe_float(value: Any, default: float | None = None) -> float | None:
    try:
        if pd.isna(value):
            return default
    except Exception:
        pass
    try:
        return float(value)
    except Exception:
        return default


def read_csv(path: str | Path) -> pd.DataFrame:
    return pd.read_csv(windows_long_path(path), encoding="utf-8-sig", sep=None, engine="python")


def read_json(path: str | Path) -> dict[str, Any]:
    with open(windows_long_path(path), "r", encoding="utf-8") as f:
        obj = json.load(f)
    if not isinstance(obj, dict):
        raise ValueError(f"JSON must be an object: {path}")
    return obj


def write_json(path: str | Path, obj: dict[str, Any]) -> None:
    p = Path(path)
    mkdirp(p.parent)
    tmp = p.with_suffix(p.suffix + ".tmp")
    with open(windows_long_path(tmp), "w", encoding="utf-8", newline="") as f:
        json.dump(obj, f, ensure_ascii=False, indent=2, sort_keys=True, default=str)
    os.replace(windows_long_path(tmp), windows_long_path(p))


def write_csv(df: pd.DataFrame, path: str | Path) -> None:
    p = Path(path)
    mkdirp(p.parent)
    df.to_csv(windows_long_path(p), index=False, encoding="utf-8-sig")


def read_jsonl(path: str | Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    if not Path(path).exists():
        return rows
    with open(windows_long_path(path), "r", encoding="utf-8") as f:
        for line in f:
            text = line.strip()
            if not text:
                continue
            try:
                obj = json.loads(text)
            except Exception:
                continue
            if isinstance(obj, dict):
                rows.append(obj)
    return rows


def normalize_profit_r(df: pd.DataFrame) -> pd.Series:
    for col in ["profit_r", "r_multiple", "result_r", "realized_r", "pnl_r"]:
        if col in df.columns:
            return pd.to_numeric(df[col], errors="coerce")
    # Last-resort fallback: use win/loss label when R is not available.
    for col in ["is_win", "win", "outcome_win"]:
        if col in df.columns:
            s = df[col].astype(str).str.lower().isin({"1", "true", "win", "winner"})
            return s.map(lambda x: 1.0 if x else -1.0)
    return pd.Series([float("nan")] * len(df), index=df.index)


def profit_factor(values: pd.Series) -> float | None:
    r = pd.to_numeric(values, errors="coerce").dropna()
    if r.empty:
        return None
    wins = float(r[r > 0].sum())
    losses = abs(float(r[r < 0].sum()))
    if losses <= 1e-12:
        return None if wins <= 1e-12 else 999.0
    return wins / losses


def win_rate(values: pd.Series) -> float | None:
    r = pd.to_numeric(values, errors="coerce").dropna()
    if r.empty:
        return None
    return float((r > 0).mean())


def avg_r(values: pd.Series) -> float | None:
    r = pd.to_numeric(values, errors="coerce").dropna()
    if r.empty:
        return None
    return float(r.mean())


def extract_tags_from_review_row(row: dict[str, Any]) -> list[tuple[str, str]]:
    pairs: set[tuple[str, str]] = set()
    key_map = [
        ("possible_risk_tags", "risk"),
        ("execution_issue_tags", "execution"),
        ("system_issue_tags", "system"),
        ("positive_tags", "positive"),
        ("possible_positive_tags", "positive"),
        ("good_sign_tags", "positive"),
        ("supporting_tags", "positive"),
    ]
    for json_key, default_group in key_map:
        tags = row.get(json_key, [])
        if isinstance(tags, str):
            tags = [x.strip() for x in tags.replace(";", ",").split(",") if x.strip()]
        if not isinstance(tags, list):
            continue
        for item in tags:
            tag = canonical_tag(item)
            if is_informative_tag(tag):
                pairs.add((tag, default_group))
    # Some ledgers store normalized tag objects in a generic list.
    generic = row.get("tags", [])
    if isinstance(generic, list):
        for item in generic:
            if isinstance(item, dict):
                tag = canonical_tag(item.get("tag_name") or item.get("name") or item.get("tag"))
                group = clean_str(item.get("tag_group") or item.get("group") or "risk")
            else:
                tag = canonical_tag(item)
                group = "risk"
            if is_informative_tag(tag):
                pairs.add((tag, group if group in TAG_GROUPS_TO_USE else "risk"))
    return sorted(pairs)


def build_trade_tag_table(feature_df: pd.DataFrame, review_rows: list[dict[str, Any]]) -> pd.DataFrame:
    keys = ["trade_id", "order_key", "payload_key"]
    feat = feature_df.copy()
    for k in keys:
        if k not in feat.columns:
            feat[k] = ""
        feat[k] = feat[k].fillna("").astype(str)
    if "strategy_id" not in feat.columns:
        raise SystemExit("feature snapshot has no strategy_id column")
    feat["profit_r_norm"] = normalize_profit_r(feat)
    tag_rows: list[dict[str, Any]] = []
    for rr in review_rows:
        base = {k: clean_str(rr.get(k)) for k in keys}
        base["strategy_id_review"] = clean_str(rr.get("strategy_id"))
        for tag, group in extract_tags_from_review_row(rr):
            row = dict(base)
            row["tag_name"] = tag
            row["tag_group"] = group
            tag_rows.append(row)
    tag_df = pd.DataFrame(tag_rows)
    if tag_df.empty:
        return pd.DataFrame()
    for k in keys:
        tag_df[k] = tag_df[k].fillna("").astype(str)
    merged = feat.merge(tag_df, on=keys, how="left")
    if "strategy_id" not in merged.columns and "strategy_id_review" in merged.columns:
        merged["strategy_id"] = merged["strategy_id_review"]
    return merged


def strategy_baseline(feature_df: pd.DataFrame) -> dict[str, dict[str, Any]]:
    out: dict[str, dict[str, Any]] = {}
    work = feature_df.copy()
    work["profit_r_norm"] = normalize_profit_r(work)
    for sid, sdf in work.groupby("strategy_id", dropna=False):
        sid = clean_str(sid)
        if not sid:
            continue
        r = sdf["profit_r_norm"]
        out[sid] = {
            "sample_count": int(r.notna().sum()),
            "win_rate": win_rate(r),
            "pf": profit_factor(r),
            "avg_r": avg_r(r),
        }
    return out


def combo_display_level(
    *,
    sample_count: int,
    win_rate_value: float | None,
    pf_value: float | None,
    avg_r_value: float | None,
    base_win_rate: float | None,
    base_pf: float | None,
    base_avg_r: float | None,
    has_positive_tag: bool,
    args: argparse.Namespace,
) -> tuple[str, str]:
    wr_delta = None if win_rate_value is None or base_win_rate is None else win_rate_value - base_win_rate
    avg_delta = None if avg_r_value is None or base_avg_r is None else avg_r_value - base_avg_r
    pf_ratio = None
    if pf_value is not None and base_pf is not None and base_pf > 1e-12 and base_pf < 900:
        pf_ratio = pf_value / base_pf

    if sample_count < args.min_combo_trades:
        return "", "sample_too_small"

    bad_avg = avg_delta is not None and avg_delta <= -abs(args.strong_avg_r_delta)
    bad_wr = wr_delta is not None and wr_delta <= -abs(args.strong_win_rate_delta)
    bad_pf = pf_ratio is not None and pf_ratio <= args.strong_pf_ratio
    if (avg_r_value is not None and avg_r_value < 0 and (bad_avg or bad_wr or bad_pf)) or (bad_avg and bad_wr):
        return "COMBO_STRONG_CAUTION", "strategy_relative_loss_heavy_combo"

    moderate_bad_avg = avg_delta is not None and avg_delta <= -abs(args.caution_avg_r_delta)
    moderate_bad_wr = wr_delta is not None and wr_delta <= -abs(args.caution_win_rate_delta)
    moderate_bad_pf = pf_ratio is not None and pf_ratio <= args.caution_pf_ratio
    if moderate_bad_avg or (moderate_bad_wr and moderate_bad_pf):
        return "COMBO_CAUTION", "strategy_relative_weak_combo"

    good_avg = avg_delta is not None and avg_delta >= abs(args.positive_avg_r_delta)
    good_wr = wr_delta is not None and wr_delta >= abs(args.positive_win_rate_delta)
    good_pf = pf_ratio is not None and pf_ratio >= args.positive_pf_ratio
    if avg_r_value is not None and avg_r_value > 0 and (good_avg or good_wr or good_pf):
        if has_positive_tag or (good_avg and good_wr):
            return "COMBO_POSITIVE_SUPPORT", "strategy_relative_positive_combo"
        return "COMBO_POSITIVE_WATCH", "strategy_relative_positive_watch_combo"

    if sample_count >= args.reference_min_combo_trades and (moderate_bad_avg or good_avg):
        return "COMBO_REFERENCE", "weak_but_visible_combo"
    return "", "not_significant"


def build_combo_rules(feature_df: pd.DataFrame, review_rows: list[dict[str, Any]], args: argparse.Namespace) -> tuple[list[dict[str, Any]], pd.DataFrame, dict[str, Any]]:
    table = build_trade_tag_table(feature_df, review_rows)
    if table.empty:
        return [], pd.DataFrame(), {"reason": "NO_TAG_TABLE"}
    baselines = strategy_baseline(feature_df)
    keys = ["trade_id", "order_key", "payload_key"]
    trade_rows: list[dict[str, Any]] = []
    for (sid, trade_id, order_key, payload_key), sdf in table.groupby(["strategy_id", *keys], dropna=False):
        sid = clean_str(sid)
        if not sid:
            continue
        tags = sorted({canonical_tag(x) for x in sdf["tag_name"].dropna().tolist() if is_informative_tag(x)})
        groups = {canonical_tag(r["tag_name"]): clean_str(r["tag_group"]) for _, r in sdf.dropna(subset=["tag_name"]).iterrows()}
        profit = safe_float(sdf["profit_r_norm"].iloc[0]) if "profit_r_norm" in sdf.columns and not sdf.empty else None
        if len(tags) < 2 or profit is None:
            continue
        trade_rows.append({
            "strategy_id": sid,
            "trade_id": clean_str(trade_id),
            "order_key": clean_str(order_key),
            "payload_key": clean_str(payload_key),
            "tags": tags,
            "tag_groups": groups,
            "profit_r": float(profit),
        })
    combo_records: list[dict[str, Any]] = []
    combo_size_range = range(2, max(2, int(args.max_combo_size)) + 1)
    for sid, rows_iter in itertools.groupby(sorted(trade_rows, key=lambda x: x["strategy_id"]), key=lambda x: x["strategy_id"]):
        rows = list(rows_iter)
        baseline = baselines.get(sid, {})
        combo_to_values: dict[tuple[str, ...], list[float]] = {}
        combo_positive_flag: dict[tuple[str, ...], bool] = {}
        for row in rows:
            tags = row["tags"]
            tag_groups = row["tag_groups"]
            for size in combo_size_range:
                if len(tags) < size:
                    continue
                for combo in itertools.combinations(tags, size):
                    combo_to_values.setdefault(combo, []).append(float(row["profit_r"]))
                    combo_positive_flag[combo] = combo_positive_flag.get(combo, False) or any(tag_groups.get(t) in POSITIVE_TAG_GROUPS for t in combo)
        for combo, vals in combo_to_values.items():
            sample_count = len(vals)
            s = pd.Series(vals, dtype=float)
            wr = win_rate(s)
            pf = profit_factor(s)
            ar = avg_r(s)
            base_wr = safe_float(baseline.get("win_rate"))
            base_pf = safe_float(baseline.get("pf"))
            base_ar = safe_float(baseline.get("avg_r"))
            display_level, reason = combo_display_level(
                sample_count=sample_count,
                win_rate_value=wr,
                pf_value=pf,
                avg_r_value=ar,
                base_win_rate=base_wr,
                base_pf=base_pf,
                base_avg_r=base_ar,
                has_positive_tag=bool(combo_positive_flag.get(combo, False)),
                args=args,
            )
            if not display_level:
                continue
            wr_delta = None if wr is None or base_wr is None else wr - base_wr
            avg_delta = None if ar is None or base_ar is None else ar - base_ar
            pf_delta = None if pf is None or base_pf is None else pf - base_pf
            combo_records.append({
                "strategy_id": sid,
                "combo_size": len(combo),
                "combo_tags": list(combo),
                "combo_key": "+".join(combo),
                "display_level": display_level,
                "reason": reason,
                "sample_count": sample_count,
                "win_rate": wr,
                "pf": pf,
                "avg_r": ar,
                "baseline_sample_count": baseline.get("sample_count"),
                "baseline_win_rate": base_wr,
                "baseline_pf": base_pf,
                "baseline_avg_r": base_ar,
                "win_rate_delta": wr_delta,
                "pf_delta": pf_delta,
                "avg_r_delta": avg_delta,
                "has_positive_tag": bool(combo_positive_flag.get(combo, False)),
            })
    if not combo_records:
        return [], pd.DataFrame(), {"reason": "NO_SIGNIFICANT_COMBOS", "trade_tag_rows": len(trade_rows)}
    df = pd.DataFrame(combo_records)
    level_order = {
        "COMBO_POSITIVE_SUPPORT": 0,
        "COMBO_POSITIVE_WATCH": 1,
        "COMBO_STRONG_CAUTION": 2,
        "COMBO_CAUTION": 3,
        "COMBO_REFERENCE": 4,
    }
    df["_level_order"] = df["display_level"].map(level_order).fillna(9)
    df["_abs_avg_delta"] = pd.to_numeric(df["avg_r_delta"], errors="coerce").abs().fillna(0.0)
    df = df.sort_values(["strategy_id", "_level_order", "sample_count", "_abs_avg_delta"], ascending=[True, True, False, False])
    df = df.groupby(["strategy_id", "display_level"], dropna=False).head(args.max_rules_per_strategy_level).copy()
    df = df.drop(columns=["_level_order", "_abs_avg_delta"])
    rules: list[dict[str, Any]] = []
    for i, (_, row) in enumerate(df.iterrows(), start=1):
        combo_tags = row.get("combo_tags")
        if not isinstance(combo_tags, list):
            combo_tags = str(row.get("combo_key", "")).split("+")
        rules.append({
            "combo_rule_id": f"GOLD_STRICT7_TAG_COMBO_{i:04d}",
            "symbol": "GOLD",
            "strategy_id": clean_str(row.get("strategy_id")),
            "combo_size": int(row.get("combo_size")),
            "combo_tags": [canonical_tag(x) for x in combo_tags if canonical_tag(x)],
            "display_level": clean_str(row.get("display_level")),
            "reason": clean_str(row.get("reason")),
            "sample_count": int(row.get("sample_count")),
            "win_rate": safe_float(row.get("win_rate")),
            "pf": safe_float(row.get("pf")),
            "avg_r": safe_float(row.get("avg_r")),
            "baseline_sample_count": safe_float(row.get("baseline_sample_count")),
            "baseline_win_rate": safe_float(row.get("baseline_win_rate")),
            "baseline_pf": safe_float(row.get("baseline_pf")),
            "baseline_avg_r": safe_float(row.get("baseline_avg_r")),
            "win_rate_delta": safe_float(row.get("win_rate_delta")),
            "pf_delta": safe_float(row.get("pf_delta")),
            "avg_r_delta": safe_float(row.get("avg_r_delta")),
            "source": "gold_strict_7_ai_review_tag_combo_strategy_relative",
            "note": "Historical AI-tag combination tendency relative to the same strategy. Informational only; no order block.",
        })
    meta = {
        "trade_tag_rows": int(len(trade_rows)),
        "combo_candidate_rows_before_trim": int(len(combo_records)),
        "combo_rules_count": int(len(rules)),
    }
    return rules, df, meta


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Append GOLD strict 7 AI-tag combo rules to numeric rules JSON.")
    p.add_argument("--ai-review-dir", type=Path, default=DEFAULT_AI_REVIEW_DIR)
    p.add_argument("--feature-snapshot-csv", type=Path, default=None)
    p.add_argument("--ai-review-jsonl", type=Path, default=None)
    p.add_argument("--rules-json", type=Path, default=DEFAULT_RULE_JSON)
    p.add_argument("--output-csv", type=Path, default=DEFAULT_OUTPUT_CSV)
    p.add_argument("--min-combo-trades", type=int, default=5)
    p.add_argument("--reference-min-combo-trades", type=int, default=3)
    p.add_argument("--max-combo-size", type=int, default=3)
    p.add_argument("--max-rules-per-strategy-level", type=int, default=12)
    p.add_argument("--strong-avg-r-delta", type=float, default=0.80)
    p.add_argument("--strong-win-rate-delta", type=float, default=0.20)
    p.add_argument("--strong-pf-ratio", type=float, default=0.55)
    p.add_argument("--caution-avg-r-delta", type=float, default=0.35)
    p.add_argument("--caution-win-rate-delta", type=float, default=0.12)
    p.add_argument("--caution-pf-ratio", type=float, default=0.75)
    p.add_argument("--positive-avg-r-delta", type=float, default=0.60)
    p.add_argument("--positive-win-rate-delta", type=float, default=0.15)
    p.add_argument("--positive-pf-ratio", type=float, default=1.35)
    return p.parse_args()


def main() -> int:
    args = parse_args()
    ai_dir = resolve(args.ai_review_dir)
    feature_csv = resolve(args.feature_snapshot_csv) if args.feature_snapshot_csv else ai_dir / "trade_feature_snapshot.csv"
    review_jsonl = resolve(args.ai_review_jsonl) if args.ai_review_jsonl else ai_dir / "trade_ai_review_ledger.jsonl"
    rules_json = resolve(args.rules_json)
    output_csv = resolve(args.output_csv)
    if not feature_csv.exists():
        raise SystemExit(f"feature snapshot CSV not found: {feature_csv}")
    if not review_jsonl.exists():
        raise SystemExit(f"AI review JSONL not found: {review_jsonl}")
    if not rules_json.exists():
        raise SystemExit(f"rules JSON not found: {rules_json}. Run build_gold_strict_7_ai_tag_numeric_rules.py first.")
    feature_df = read_csv(feature_csv)
    review_rows = read_jsonl(review_jsonl)
    rules_obj = read_json(rules_json)
    combo_rules, combo_df, combo_meta = build_combo_rules(feature_df, review_rows, args)
    rules_obj["combo_rules_schema_version"] = SCHEMA_VERSION
    rules_obj["combo_rules_created_at_utc"] = utc_now_text()
    rules_obj["combo_rules_count"] = int(len(combo_rules))
    rules_obj["combo_rules_meta"] = combo_meta
    rules_obj["combo_rules_settings"] = {
        "min_combo_trades": int(args.min_combo_trades),
        "reference_min_combo_trades": int(args.reference_min_combo_trades),
        "max_combo_size": int(args.max_combo_size),
        "max_rules_per_strategy_level": int(args.max_rules_per_strategy_level),
        "strong_avg_r_delta": float(args.strong_avg_r_delta),
        "strong_win_rate_delta": float(args.strong_win_rate_delta),
        "strong_pf_ratio": float(args.strong_pf_ratio),
        "caution_avg_r_delta": float(args.caution_avg_r_delta),
        "caution_win_rate_delta": float(args.caution_win_rate_delta),
        "caution_pf_ratio": float(args.caution_pf_ratio),
        "positive_avg_r_delta": float(args.positive_avg_r_delta),
        "positive_win_rate_delta": float(args.positive_win_rate_delta),
        "positive_pf_ratio": float(args.positive_pf_ratio),
    }
    rules_obj["combo_rules"] = combo_rules
    # Keep cycle_ok inherited from the single-tag builder. Empty combo rules are allowed.
    write_json(rules_json, rules_obj)
    if combo_df.empty:
        write_csv(pd.DataFrame(columns=[
            "strategy_id", "combo_size", "combo_key", "display_level", "reason", "sample_count",
            "win_rate", "pf", "avg_r", "baseline_win_rate", "baseline_pf", "baseline_avg_r",
            "win_rate_delta", "pf_delta", "avg_r_delta",
        ]), output_csv)
    else:
        out_df = combo_df.copy()
        if "combo_tags" in out_df.columns:
            out_df["combo_tags"] = out_df["combo_tags"].apply(lambda x: "+".join(x) if isinstance(x, list) else str(x))
        write_csv(out_df, output_csv)
    print(json.dumps({
        "cycle_ok": True,
        "combo_rules_count": int(len(combo_rules)),
        "rules_json": str(rules_json),
        "output_csv": str(output_csv),
        "combo_meta": combo_meta,
    }, ensure_ascii=False, indent=2, default=str), flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
